### ISSUE TITLE
关于宏包\usepackage{subfigure}冲突

### ISSUE THREAD

**Issue by ElenHuo** [Gnomeek/GDUT-UndergraduateThesis#1]
你好，使用subfigure的时候宏包会发生冲突

**Comment by Gnomeek** [comment]
可以发log截图看下吗，我还没遇到这样的问题

**Comment by Gnomeek** [comment]
我的subfigure可以正常编译
![image](https://user-images.githubusercontent.com/19972493/76165779-bea8a980-6194-11ea-9a10-f9c3809bde0d.png)

**Comment by ElenHuo** [comment]
那就是我win系统有的底层没配置好，谢谢

**Comment by ElenHuo** [comment]
解决了，因为习惯用旧包\subfigure。 \subfig和以前的\subfigure用法有区别。
建议加个tips提醒一下\subfig的用法。
谢谢你的回复和模板，用得很舒服

**Comment by Gnomeek** [comment]
好的，我是在这个[repo](https://github.com/Daniel612/gdutthesis)基础上改了些细节，优化了表格样式，字体什么的。有问题可以继续发issue
